### ISSUE TITLE
Unable to connect to Kuksa databroker server

### ISSUE THREAD

**Issue by TheLittleNaruto** [eclipse-kuksa/kuksa-python-sdk#33]
Hi 

I am trying Kuksa python SDK to connect to kuksa databroker. However it fails to connect. 
## To start the databroker server:
```
tln@tln-X550LD:~/Kuksa$ sudo docker run -it --rm --name Server --network kuksa ghcr.io/eclipse-kuksa/kuksa-databroker:main --insecure
[sudo] password for tln: 
2024-06-16T12:35:01.443571Z  INFO databroker: Init logging from RUST_LOG (environment variable not found)
2024-06-16T12:35:01.443589Z  INFO databroker: Starting Kuksa Databroker 0.4.6
2024-06-16T12:35:01.444322Z  INFO databroker: Populating metadata from file 'vss_release_4.0.json'
2024-06-16T12:35:01.726938Z  WARN databroker: Authorization is not enabled.
2024-06-16T12:35:01.727027Z  INFO databroker::broker: Starting housekeeping task
2024-06-16T12:35:01.727055Z  INFO databroker::grpc::server: Listening on 0.0.0.0:55555
2024-06-16T12:35:01.727065Z  INFO databroker::grpc::server: TLS is not enabled
2024-06-16T12:35:01.727073Z  INFO databroker::grpc::server: Authorization is not enabled.
```
## To verify the connect, ran the databroker-cli

```
tln@tln-X550LD:~/Kuksa$ sudo docker run -it --rm --network kuksa ghcr.io/eclipse-kuksa/kuksa-databroker-cli:main --server Server:55555
Using kuksa.val.v1

  ⠀⠀⠀⢀⣤⣶⣾⣿⢸⣿⣿⣷⣶⣤⡀
  ⠀⠀⣴⣿⡿⠋⣿⣿⠀⠀⠀⠈⠙⢿⣿⣦⠀
  ⠀⣾⣿⠋⠀⠀⣿⣿⠀⠀⣶⣿⠀⠀⠙⣿⣷   
  ⣸⣿⠇⠀⠀⠀⣿⣿⠠⣾⡿⠃⠀⠀⠀⠸⣿⣇⠀⠀⣶⠀⣠⡶⠂⠀⣶⠀⠀⢰⡆⠀⢰⡆⢀⣴⠖⠀⢠⡶⠶⠶⡦⠀⠀⠀⣰⣶⡀
  ⣿⣿⠀⠀⠀⠀⠿⢿⣷⣦⡀⠀⠀⠀⠀⠀⣿⣿⠀⠀⣿⢾⣏⠀⠀⠀⣿⠀⠀⢸⡇⠀⢸⡷⣿⡁⠀⠀⠘⠷⠶⠶⣦⠀⠀⢠⡟⠘⣷
  ⢹⣿⡆⠀⠀⠀⣿⣶⠈⢻⣿⡆⠀⠀⠀⢰⣿⡏⠀⠀⠿⠀⠙⠷⠄⠀⠙⠷⠶⠟⠁⠀⠸⠇⠈⠻⠦⠀⠐⠷⠶⠶⠟⠀⠠⠿⠁⠀⠹⠧
  ⠀⢿⣿⣄⠀⠀⣿⣿⠀⠀⠿⣿⠀⠀⣠⣿⡿
  ⠀⠀⠻⣿⣷⡄⣿⣿⠀⠀⠀⢀⣠⣾⣿⠟    databroker-cli                
  ⠀⠀⠀⠈⠛⠇⢿⣿⣿⣿⣿⡿⠿⠛⠁     v0.4.6                        

Successfully connected to http://Server:55555/
kuksa.val.v1 > publish Vehicle.Speed 42
[publish]  OK  
kuksa.val.v1 > get Vehicle.Speed
[get]  OK  
Vehicle.Speed: 42.00 km/h
kuksa.val.v1 > 
```

As we can see, it is able to publish to the databroker and get it back. 
## Now used kuksa python sdk to achieve the same:
```
tln@tln-X550LD:~/Kuksa/trying-kuksa-python-sdk$ python3 -m venv env
tln@tln-X550LD:~/Kuksa/trying-kuksa-python-sdk$ source env/bin/activate
(env) tln@tln-X550LD:~/Kuksa/trying-kuksa-python-sdk$ pip install kuksa-client
```
## Now ran the kuksa-client command

```
(env) tln@tln-X550LD:~/Kuksa/trying-kuksa-python-sdk$ kuksa-client
```

But this resulted in below error:

```

     ⢀⣤⣶⣾⣿⢸⣿⣿⣷⣶⣤⡀
    ⣴⣿⡿⠋⣿⣿   ⠈⠙⢿⣿⣦
   ⣾⣿⠋  ⣿⣿  ⣶⣿  ⠙⣿⣷
  ⣸⣿⠇   ⣿⣿⠠⣾⡿⠃   ⠸⣿⣇  ⣶ ⣠⡶⠂ ⣶  ⢰⡆ ⢰⡆⢀⣴⠖ ⢠⡶⠶⠶⡦   ⣰⣶⡀
  ⣿⣿    ⠿⢿⣷⣦⡀     ⣿⣿  ⣿⢾⣏   ⣿  ⢸⡇ ⢸⡷⣿⡁  ⠘⠷⠶⠶⣦  ⢠⡟⠘⣷
  ⢹⣿⡆   ⣿⣶⠈⢻⣿⡆   ⢰⣿⡏  ⠿ ⠙⠷⠄ ⠙⠷⠶⠟⠁ ⠸⠇⠈⠻⠦ ⠐⠷⠶⠶⠟ ⠠⠿⠁ ⠹⠧
   ⢿⣿⣄  ⣿⣿  ⠿⣿  ⣠⣿⡿
    ⠻⣿⣷⡄⣿⣿   ⢀⣠⣾⣿⠟    kuksa-client CLI
     ⠈⠛⠇⢿⣿⣿⣿⣿⡿⠿⠛⠁     0.4.3


Connecting to VSS server at 127.0.0.1 port 55555 using KUKSA GRPC protocol.
TLS will not be used.
2024-06-16 17:59:41,321 INFO kuksa_client.grpc: No Root CA present, it will not be possible to use a secure connection!
2024-06-16 17:59:41,321 INFO kuksa_client.grpc.aio: Establishing insecure channel
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/tln/Kuksa/trying-kuksa-python-sdk/env/lib/python3.11/site-packages/kuksa_client/grpc/aio.py", line 386, in get_server_info
    resp = await self.client_stub.GetServerInfo(req, **rpc_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tln/Kuksa/trying-kuksa-python-sdk/env/lib/python3.11/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:55555: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-06-16T17:59:41.323376945+05:30", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:55555: Failed to connect to remote host: Connection refused"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/tln/Kuksa/trying-kuksa-python-sdk/env/lib/python3.11/site-packages/kuksa_client/__init__.py", line 118, in run
    self.loop.run_until_complete(self.backend.mainLoop())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tln/Kuksa/trying-kuksa-python-sdk/env/lib/python3.11/site-packages/kuksa_client/cli_backend/grpc.py", line 276, in mainLoop
    async with kuksa_client.grpc.aio.VSSClient(self.serverIP, self.serverPort, token=self.token) as vss_client:
  File "/home/tln/Kuksa/trying-kuksa-python-sdk/env/lib/python3.11/site-packages/kuksa_client/grpc/aio.py", line 61, in __aenter__
    await self.connect()
  File "/home/tln/Kuksa/trying-kuksa-python-sdk/env/lib/python3.11/site-packages/kuksa_client/grpc/aio.py", line 87, in connect
    logger.debug("Connected to server: %s", await self.get_server_info())
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tln/Kuksa/trying-kuksa-python-sdk/env/lib/python3.11/site-packages/kuksa_client/grpc/aio.py", line 102, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tln/Kuksa/trying-kuksa-python-sdk/env/lib/python3.11/site-packages/kuksa_client/grpc/aio.py", line 393, in get_server_info
    raise VSSClientError.from_grpc_error(exc) from exc
kuksa_client.grpc.VSSClientError: ({'code': 14, 'reason': 'unavailable', 'message': 'failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:55555: Failed to connect to remote host: Connection refused'}, [])
Error: Websocket could not be connected or the gRPC channel could not be created.
2024-06-16 17:59:47,321 INFO kuksa_client.cli_backend.grpc: gRPC channel disconnected.
```
Could you please help what went wrong here? BTW I also tried to manually connect to databroker, by running below command:

```
Test Client> connect http://Server:55555
Invalid server URI. Unsupported protocol: http
```
And it did not work, but same command works on Kuksa databroker-cli.

**Comment by wba2hi** [comment]
Can you try again to connect using `kuksa-client grpc://Server:55555` (instead of `http://Server:55555`)?

Kuksa-Client supports two different protocols, where each uses a custom URI format. On one hand the protocol `grpc://` to establish a connection using gRPC and on the other hand `ws://` to establish a connection using Websockets. In case TLS is being used it be `grpcs://...`and `wss://`

**Comment by TheLittleNaruto** [comment]
> Can you try again to connect using `kuksa-client grpc://Server:55555` (instead of `http://Server:55555`)?
> 
> Kuksa-Client supports two different protocols, where each uses a custom URI format. On one hand the protocol `grpc://` to establish a connection using gRPC and on the other hand `ws://` to establish a connection using Websockets. In case TLS is being used it is `grpcs://...`and `wss://`

I tried both of them, but same error. @wba2hi

**Comment by SebastianSchildt** [comment]
Can you double check, whether the error is the **same**, because the original error message said, it does not recognize `http`, so if you replacaed that with e.g. `grpc://` I would at least expect a different error

**Comment by SebastianSchildt** [comment]
Also you used a docker network "kuksa", are you sure this is reachable from "outside" (because you use venv directly on host  for client).  I think at least under Linux this may require some routing being set up. 

A simple way to test is, instead of using a custom  network, use host mode in docker, i.e. start

```
sudo docker run -it --rm --name Server --net=host ghcr.io/eclipse-kuksa/kuksa-databroker:main --insecure
```

And then try connecting wiht kuksa-client again (using the IP or hostname of your computer)

**Comment by thu4n** [comment]
I actually had the same error with `StatusCode.UNAVAILABLE` when using the SDK. I managed to fix this by downgrading the Kuksa Databroker version to `0.4.4` instead of the latest version.

**Comment by erikbosch** [comment]
Hi @raghulrajn!

How did you start the Databroker and which version are you using? There have been some recent refactoring so it is not certain that all databroker/kuksa-python-sdk version combinations match. The kuksa website starter guide is also a bit outdated, we are working on updating it.

From the message I suggest the first thing to check is if the Databroker actually is reachable

```
# If Databroker is running and listening on 127.0.0.1:55555
erik@debian6:~$ curl 127.0.0.1:55555
curl: (1) Received HTTP/0.9 when not allowed

# If Databroker is down or not reachable
erik@debian6:~$ curl 127.0.0.1:55555
curl: (7) Failed to connect to 127.0.0.1 port 55555 after 0 ms: Couldn't connect to server
```

**Comment by raghulrajn** [comment]
Thank you @erikbosch 
I ensured that gRPC server was running at the mentioned 127.0.0.1:55555. 

I tried using native gRPC library, I got no issues on sending and receiving the data. through same port. But when I tried to send and receive data using Kuksa client. Below is the error I got. 
```
kuksa_client.grpc.VSSClientError: ({'code': 12, 'reason': 'unimplemented', 'message': 'Method not found!'}, [])
```
## System information
- kuksa_client 0.4.3, 0.4.2, 0.4.1
- libprotoc 27.2
- python 3.10

**Comment by erikbosch** [comment]
Hi!

I need some more info to try to help.

- As I understand you run on of the examples at https://github.com/eclipse-kuksa/kuksa-python-sdk/blob/main/docs/examples/async-grpc.md, but which one of them?
- How do you start Kuksa Databroker, i.e. which version are you using?

**Comment by raghulrajn** [comment]
I ran the Vehicle.Speed publishing and subscribing example. 
I started the kuksa databroker 0.4.7-dev.0
```console
2024-11-13T18:00:27.507963Z  INFO databroker: Init logging from RUST_LOG (environment variable not found)
2024-11-13T18:00:27.507978Z  INFO databroker: Starting Kuksa Databroker 0.4.7-dev.0
2024-11-13T18:00:27.507982Z  INFO databroker: Using 8 threads with 8 cores available on the system
2024-11-13T18:00:27.508509Z  INFO databroker: Populating metadata from file 'vss_release_4.0.json'
2024-11-13T18:00:27.513569Z  WARN databroker: Authorization is not enabled.
2024-11-13T18:00:27.513614Z  INFO databroker::broker: Starting housekeeping task
2024-11-13T18:00:27.513628Z  INFO databroker::grpc::server: Listening on 0.0.0.0:55555
2024-11-13T18:00:27.513632Z  INFO databroker::grpc::server: TLS is not enabled
2024-11-13T18:00:27.513636Z  INFO databroker::grpc::server: Authorization is not enabled.
```

It would be helpful, if you provide the right steps to follow to develop a kuksa application using python. 

Thank you

**Comment by erikbosch** [comment]
Hi again!

I was not able to reproduce any problems. Here I try to show what I did, it would be good if you could do the same and provide your output if they differ.

*The version identifier `0.4.7-dev.0` is an unreleased development version, so result may vary depending on which commit is used as base. If you build from source, provide info on which commit you use as base or update to latest. If you run from Docker container `ghcr.io/eclipse-kuksa/kuksa-databroker:main` pull a new one, or provide info on which `sha` you use so i could try to test that particular build. You may also opt for using the latest released version instead.*

# Starting latest Databroker from main

```
erik@debian6:~/kuksa-databroker$ git log -1
commit 95dcfcf79b08255041e24d556eb32f4daec459b2 (HEAD, upstream/main)
Author: Erik Jaegervall <erik.jaegervall@se.bosch.com>
Date:   Wed Nov 13 16:39:08 2024 +0100

    Fixing links
    
    COVESA documentation was partially refactored recently.
erik@debian6:~/kuksa-databroker$ cargo run --bin databroker -- --metadata data/vss-core/vss_release_4.0.json --insecure
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/databroker --metadata data/vss-core/vss_release_4.0.json --insecure`
2024-11-14T07:52:15.228926Z  INFO databroker: Init logging from RUST_LOG (environment variable not found)
2024-11-14T07:52:15.228992Z  INFO databroker: Starting Kuksa Databroker 0.4.7-dev.0
2024-11-14T07:52:15.229001Z  INFO databroker: Using 3 threads with 3 cores available on the system
2024-11-14T07:52:15.231349Z  INFO databroker: Populating metadata from file 'data/vss-core/vss_release_4.0.json'
2024-11-14T07:52:15.261445Z  WARN databroker: Authorization is not enabled.
2024-11-14T07:52:15.261628Z  INFO databroker::grpc::server: Notifying systemd that the service is ready
2024-11-14T07:52:15.261653Z  INFO databroker::broker: Starting housekeeping task
2024-11-14T07:52:15.261710Z  INFO databroker::grpc::server: Listening on 127.0.0.1:55555
2024-11-14T07:52:15.261729Z  INFO databroker::grpc::server: TLS is not enabled
2024-11-14T07:52:15.261739Z  INFO databroker::grpc::server: Authorization is not enabled.
```



# Installing an starting kuksa-client to have library installed and CLI
```

erik@debian6:~/vss-tools$ pip install -U kuksa-client
Defaulting to user installation because normal site-packages is not writeable
...
erik@debian6:~/vss-tools$ kuksa-client

     ⢀⣤⣶⣾⣿⢸⣿⣿⣷⣶⣤⡀
    ⣴⣿⡿⠋⣿⣿   ⠈⠙⢿⣿⣦
   ⣾⣿⠋  ⣿⣿  ⣶⣿  ⠙⣿⣷
  ⣸⣿⠇   ⣿⣿⠠⣾⡿⠃   ⠸⣿⣇  ⣶ ⣠⡶⠂ ⣶  ⢰⡆ ⢰⡆⢀⣴⠖ ⢠⡶⠶⠶⡦   ⣰⣶⡀
  ⣿⣿    ⠿⢿⣷⣦⡀     ⣿⣿  ⣿⢾⣏   ⣿  ⢸⡇ ⢸⡷⣿⡁  ⠘⠷⠶⠶⣦  ⢠⡟⠘⣷
  ⢹⣿⡆   ⣿⣶⠈⢻⣿⡆   ⢰⣿⡏  ⠿ ⠙⠷⠄ ⠙⠷⠶⠟⠁ ⠸⠇⠈⠻⠦ ⠐⠷⠶⠶⠟ ⠠⠿⠁ ⠹⠧
   ⢿⣿⣄  ⣿⣿  ⠿⣿  ⣠⣿⡿
    ⠻⣿⣷⡄⣿⣿   ⢀⣠⣾⣿⠟    kuksa-client CLI
     ⠈⠛⠇⢿⣿⣿⣿⣿⡿⠿⠛⠁     0.4.3


Connecting to VSS server at 127.0.0.1 port 55555 using KUKSA GRPC protocol.
TLS will not be used.
2024-11-14 08:54:10,540 INFO kuksa_client.grpc: No Root CA present, it will not be possible to use a secure connection!
2024-11-14 08:54:10,541 INFO kuksa_client.grpc.aio: Establishing insecure channel
2024-11-14 08:54:10,591 INFO kuksa_client.cli_backend.grpc: gRPC channel connected.
Test Client> setValue Vehicle.Speed 43
OK

Test Client> getValue Vehicle.Speed
{
    "path": "Vehicle.Speed",
    "value": {
        "value": 43.0,
        "timestamp": "2024-11-14T07:54:20.944022+00:00"
    }
}

Test Client> 

```

# Running first example

From https://github.com/eclipse-kuksa/kuksa-python-sdk/blob/main/docs/examples/async-grpc.md

```
import asyncio

from kuksa_client.grpc.aio import VSSClient

async def main():
    async with VSSClient('127.0.0.1', 55555) as client:
        current_values = await client.get_current_values([
            'Vehicle.Speed',
        ])
        if current_values['Vehicle.Speed'] is not None:
            print(current_values['Vehicle.Speed'].value)

asyncio.run(main())
```

Results in

```
erik@debian6:~$ python speed1.py 
43.0
```

Second example gives same output

# Running Feeder example
```

import asyncio
import random

from kuksa_client.grpc import Datapoint
from kuksa_client.grpc import DataEntry
from kuksa_client.grpc import DataType
from kuksa_client.grpc import EntryUpdate
from kuksa_client.grpc import Field
from kuksa_client.grpc import Metadata
from kuksa_client.grpc.aio import VSSClient

async def read_speed_from_can_bus():
    """Stub of a real coroutine that would read vehicle speed from CAN bus."""
    await asyncio.sleep(0.1)
    return random.randrange(250)

async def main():
    async with VSSClient('127.0.0.1', 55555) as client:
        while True:
            new_speed = await read_speed_from_can_bus()
            updates = (EntryUpdate(DataEntry(
                'Vehicle.Speed',
                value=Datapoint(value=new_speed),
                metadata=Metadata(data_type=DataType.FLOAT),
            ), (Field.VALUE,)),)
            await client.set(updates=updates)

asyncio.run(main())
```

No output seen when running it:

`erik@debian6:~$ python speedfeeder.py 
`

But in Kuksa-client you can see that value changes:

```
Test Client> getValue Vehicle.Speed
{
    "path": "Vehicle.Speed",
    "value": {
        "value": 178.0,
        "timestamp": "2024-11-14T08:00:32.302392+00:00"
    }
}

Test Client> getValue Vehicle.Speed
{
    "path": "Vehicle.Speed",
    "value": {
        "value": 82.0,
        "timestamp": "2024-11-14T08:00:33.475646+00:00"
    }
}
```

**Comment by raghulrajn** [comment]
Hello Erik, 

Compiling and running from the Source helped to solve the issue. Thank you for helping out here. 

Regards
Raghul
